src/config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Аспирантура КГTY'

urlpatterns = [
    path('', include('main.urls')),
    path("admin/", admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('applications/', include('applications.urls')),
    path('faculty/', include('faculties.urls')),
    path('postgraduates/', include('postgraduates.urls', namespace='postgraduates')),
    path('all_study_plans/', include('study_plans.urls', namespace='all_study_plans')),
    path('study_plans/', include('study_plans.urls', namespace='student_study_plans')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/main/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    re_path(r'^login/$', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

src/profiles/urls.py
from django.urls import URLPattern, path
from .views import *

app_name = 'profiles'

urlpatterns = [
    path('student_profile', ShowStudentProfile.as_view(), name='student_profile'),
    path('edit_student_profile', EditStudentProfile.as_view(), name='edit_student_profile'),
    path('supervisor_profile', ShowSupervisorProfile.as_view(), name='supervisor_profile'),
    path('edit_supervisor_profile', EditSupervisorProfile.as_view(), name='edit_supervisor_profile'),
    path("password_change", PasswordChange.as_view(), name="password_change"),
]

src/profiles/models.py
from io import open_code
from tokenize import blank_re
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField

class Gender(models.TextChoices):
    NONE = 'NA', 'Не задано'
    MALE = 'M', 'Мужчина'
    FEMALE = 'F', 'Женщина'

class Education(models.Model):
    code = models.CharField(max_length=10, blank=False)
    name = models.CharField(max_length=50, blank=False)

    class Meta:
        verbose_name = 'Уровень образования'
        verbose_name_plural = 'Уровни образования'
        ordering = ['name']

    def __str__(self):
        return self.name

class Country(models.Model):
    code = models.CharField(max_length=10, blank=False)
    name = models.CharField(max_length=50, blank=False)

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Справочник стран'
        ordering = ['name']

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    middle_name = models.CharField(max_length=150, blank=True, null=True)
    mobile = PhoneNumberField(blank=True, null=True)
    personal_number = models.CharField(blank=True, null=True, max_length=20)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    gender = models.CharField(
        max_length=2,
        choices=Gender.choices,
        default=Gender.NONE,
    )

class ContactDetails(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    document_name = models.CharField(max_length=50, blank=False)
    document_code = models.CharField(max_length=10, blank=False)
    document_number = models.CharField(max_length=10, blank=False)
    issue_date = models.DateField(blank=False)
    issued_by = models.CharField(max_length=50, blank=False)
    birthdate_place = models.CharField(max_length=100, blank=False)
    education_level = models.ForeignKey(Education, on_delete=models.SET_NULL, blank=True, null=True)
    citizenship = models.ForeignKey(Country, on_delete=models.SET_NULL, blank=True, null=True)

class EducationalDocument(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='educational_documents')
    number = models.CharField(max_length=50, blank=False)
    issued_date = models.DateField(blank=False)
    organization = models.CharField(max_length=200, blank=False)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

src/profiles/forms.py
from django import forms
from django.forms.widgets import DateInput, EmailInput, NumberInput
from django.contrib.auth.forms import SetPasswordForm

from .models import *

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

        labels = {
            'first_name': 'Имя:', 
            'last_name': 'Фамилия', 
            'email': 'Эл.почта:'
        }

        widgets = {
            'first_name': forms.TextInput(attrs={ 'class': 'form-control', 'required': "true" }),
            'last_name': forms.TextInput(attrs={ 'class': 'form-control', 'required': "true"  }),
            'email': forms.EmailInput(attrs={ 'class': 'form-control',  'required': "true" })
        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo', 'middle_name', 'mobile', 'personal_number', 'birth_date', 'gender')

        labels = {
            'photo': 'Фотография',
            'middle_name': 'Отчество:', 
            'mobile': 'Номер телефона:', 
            'personal_number': 'ИИН:',
            'birth_date': 'Дата рождения:',
            'gender': 'Пол:'
        }

        widgets = {
            'middle_name': forms.TextInput(attrs={ 'class': 'form-control' }),
            'mobile': forms.TextInput(attrs={ 'class': 'form-control', 'required': "true"  }),
            'email': forms.TextInput(attrs={ 'class': 'form-control', 'required': "true" }),
            'personal_number': forms.TextInput(attrs={ 'class': 'form-control', 'required': "true" }),
            'birth_date': NumberInput(attrs={ 'type': 'date', 'class': 'form-control' })
        }

# forms.DateField(widget=NumberInput(attrs={'type': 'date'}))

class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ('current_password', 'new_password1', 'new_password2')

    current_password = forms.CharField(max_length=50, label='Текущий пароль',
                        widget=forms.PasswordInput(attrs={'class':'form-control', 'id':"password", 'placeholder':'Текущий пароль'}))

    new_password1 = forms.CharField(max_length=50, label='Новый пароль',
                        widget=forms.PasswordInput(attrs={'class':'form-control', 'id':"password", 'placeholder':'Новый пароль'}))
    
    new_password2 = forms.CharField(max_length=50, label='Подтверждение нового пароля',
                        widget=forms.PasswordInput(attrs={'class':'form-control', 'id':"password", 'placeholder':'Подтверждение нового пароля'}))

    def clean_current_password(self):
        current_password = self.cleaned_data['current_password']
        user = self.user
        if user.check_password(current_password):
            return current_password
        else:
            raise forms.ValidationError('Текущий пароль не совпадает с паролем пользователя!')

src/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, ListView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib import messages

from .models import *
from main.models import MenuItems
from main.views import StudentMenuView, SupervisorMenuView, UserGroupBasedMenuView
from faculties.forms import SupervisorForm
from .forms import *

class ShowStudentProfile(LoginRequiredMixin, StudentMenuView, View):
    template_name = 'profiles/show_student_profile.html'
    login_url = '/login/'

    def get_context_data(self, request, *args,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = request.user
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request)
        return render(request, self.template_name, context)

class EditStudentProfile(LoginRequiredMixin, StudentMenuView, View):
    """
    End point to edit a student profile.
    """
    template_name = 'profiles/edit_student_profile.html'
    login_url = '/login/'

    def get_context_data(self, request, *args,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = request.user
        context['user_form'] = UserForm(instance=request.user)
        context['profile_form'] = ProfileForm(instance=request.user.profile)
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Ваш профиль был успешно обновлен!')
            return redirect('profiles:student_profile')
        else:
            for error in list(user_form.errors.values()):
                messages.error(request, error)
            for error in list(profile_form.errors.values()):
                messages.error(request, error)
            context = self.get_context_data(request)
            return render(request, self.template_name, context)

class ShowSupervisorProfile(LoginRequiredMixin, SupervisorMenuView, View):
    template_name = 'profiles/show_supervisor_profile.html'
    login_url = '/login/'

    def get_context_data(self, request, *args,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = request.user
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request)
        return render(request, self.template_name, context)

class EditSupervisorProfile(LoginRequiredMixin, SupervisorMenuView, View):
    """
    End point to edit a supervisor profile.
    """
    template_name = 'profiles/edit_supervisor_profile.html'
    login_url = '/login/'

    def get_context_data(self, request, *args,**kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = request.user
        context['user_form'] = UserForm(instance=request.user)
        context['profile_form'] = ProfileForm(instance=request.user.profile)
        context['supervisor_form'] = SupervisorForm(instance=request.user.supervisor)
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        supervisor_form = SupervisorForm(request.POST, instance=request.user.supervisor)
        if user_form.is_valid() and profile_form.is_valid() and supervisor_form.is_valid():
            user_form.save()
            profile_form.save()
            supervisor_form.save()
            messages.success(request, 'Ваш профиль был успешно обновлен!')
            return redirect('profiles:supervisor_profile')
        else:
            for error in list(user_form.errors.values()):
                messages.error(request, error)
            for error in list(profile_form.errors.values()):
                messages.error(request, error)
            for error in list(supervisor_form.errors.values()):
                messages.error(request, error)
            context = self.get_context_data(request)
            return render(request, self.template_name, context)

class PasswordChange(LoginRequiredMixin, View):
    form_class = SetPasswordForm
    template_name = 'profiles/password_reset_confirm.html'
    login_url = '/login/'

    def get_context_data(self, request, *args,**kwargs):
        # context = super().get_context_data(**kwargs)
        user = request.user
        user_group = user.groups.first()
        context = {
            'user': user,
            'form': self.form_class(user),
            'menu': MenuItems.objects.filter(is_active=True, seen_by=user_group.id)
        }
        return context

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            context = self.get_context_data(request)
            return render(request, self.template_name, context)
        return redirect('login')

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user = request.user
            form = self.form_class(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Ваш пароль был успешно изменен.")
                return redirect('login')
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)
                context = self.get_context_data(request)
                return render(request, self.template_name, context)

src/profiles/templates/profiles/edit_student_profile.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %} 
{% block title %}Application Polytech{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}?{% now 'U' %}"/>
{% endblock %}

{% block page_content %}
<div class="main_block_section col-sm-6 mb-3">
    <h3 class="fs-4 col-sm-12">Редактировать мой профиль</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group row mb-2 text-sm-start">
            <label for="first_name" class="col-sm-4 col-form-label fs-5">{{ user_form.first_name.label_tag }}</label>
            <div class="col_value col-sm-6">{{ user_form.first_name }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="last_name" class="col-sm-4 col-form-label fs-5">{{ user_form.last_name.label_tag }}</label>
            <div class="col_value col-sm-6">{{ user_form.last_name }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="middle_name" class="col-sm-4 col-form-label fs-5">{{ profile_form.middle_name.label_tag }}</label>
            <div class="col_value col-sm-6">{{ profile_form.middle_name }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="mobile" class="col-sm-4 col-form-label fs-5">{{ profile_form.mobile.label_tag }}</label>
            <div class="col_value col-sm-6">{{ profile_form.mobile }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="email" class="col-sm-4 col-form-label fs-5">{{ user_form.email.label_tag }}</label>
            <div class="col_value col-sm-6">{{ user_form.email }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="personal_number" class="col-sm-4 col-form-label fs-5">{{ profile_form.personal_number.label_tag }}</label>
            <div class="col_value col-sm-6">{{ profile_form.personal_number }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="birth_date" class="col-sm-4 col-form-label fs-5">{{ profile_form.birth_date.label_tag }}</label>
            <div class="col_value col-sm-6">{{ profile_form.birth_date }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="gender" class="col-sm-4 col-form-label fs-5">{{ profile_form.gender.label_tag }}</label>
            <div class="col_value col-sm-6">
                {% render_field profile_form.gender class="form-select" id="gender" aria-label="gender" %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 d-flex justify-content-between">
                <button class="btn btn-primary col-sm-4" type="submit">Сохранить</button>
                <a href="{% url 'profiles:student_profile' %}" class="btn btn-secondary col-sm-4 me-0">Отмена</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

src/profiles/templates/profiles/edit_supervisor_profile.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %} 
{% block title %}Application Polytech{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}?{% now 'U' %}"/>
{% endblock %}

{% block page_content %}
<div class="main_block_section col-sm-6 mb-3">
    <h3 class="fs-4 col-sm-12">Редактировать мой профиль</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group row mb-2 text-sm-start">
            <label for="first_name" class="col-sm-4 col-form-label fs-5">{{ user_form.first_name.label_tag }}</label>
            <div class="col_value col-sm-6">{{ user_form.first_name }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="last_name" class="col-sm-4 col-form-label fs-5">{{ user_form.last_name.label_tag }}</label>
            <div class="col_value col-sm-6">{{ user_form.last_name }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="middle_name" class="col-sm-4 col-form-label fs-5">{{ profile_form.middle_name.label_tag }}</label>
            <div class="col_value col-sm-6">{{ profile_form.middle_name }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="mobile" class="col-sm-4 col-form-label fs-5">{{ profile_form.mobile.label_tag }}</label>
            <div class="col_value col-sm-6">{{ profile_form.mobile }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="email" class="col-sm-4 col-form-label fs-5">{{ user_form.email.label_tag }}</label>
            <div class="col_value col-sm-6">{{ user_form.email }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="personal_number" class="col-sm-4 col-form-label fs-5">{{ profile_form.personal_number.label_tag }}</label>
            <div class="col_value col-sm-6">{{ profile_form.personal_number }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="birth_date" class="col-sm-4 col-form-label fs-5">{{ profile_form.birth_date.label_tag }}</label>
            <div class="col_value col-sm-6">{{ profile_form.birth_date }}</div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="gender" class="col-sm-4 col-form-label fs-5">{{ profile_form.gender.label_tag }}</label>
            <div class="col_value col-sm-6">
                {% render_field profile_form.gender class="form-select" id="gender" aria-label="gender" %}
            </div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="department" class="col-sm-4 col-form-label fs-5">{{ supervisor_form.department.label_tag }}</label>
            <div class="col_value col-sm-6">
                {% render_field supervisor_form.department class="form-select" id="department" aria-label="department" %}
            </div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="academic_title" class="col-sm-4 col-form-label fs-5">{{ supervisor_form.academic_title.label_tag }}</label>
            <div class="col_value col-sm-6">
                {% render_field supervisor_form.academic_title class="form-select" id="academic_title" aria-label="academic_title" %}
            </div>
        </div>
        <div class="form-group row mb-2 text-sm-start">
            <label for="academic_degree" class="col-sm-4 col-form-label fs-5">{{ supervisor_form.academic_degree.label_tag }}</label>
            <div class="col_value col-sm-6">
                {% render_field supervisor_form.academic_degree class="form-select" id="academic_degree" aria-label="academic_degree" %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 d-flex justify-content-between">
                <button class="btn btn-primary col-sm-4" type="submit">Сохранить</button>
                <a href="{% url 'profiles:supervisor_profile' %}" class="btn btn-secondary col-sm-4 me-0">Отмена</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

src/profiles/templates/profiles/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %} 
{% block title %}Application Polytech{% endblock %}

{% block style_head %} {% endblock %}

{% block page_content %}
<div class="main_block_section col-sm-6 mb-3">
    <h3 class="fs-3 col-sm-8 text-uppercase text-sm-center">Смена пароля</h3>
    <!-- {% if form.errors %}
       {% for field in form %}
           {% for error in field.errors %} 
              <div class="alert alert-danger">
                   <strong>{{ error|escape }}</strong>
              </div>
           {% endfor %}
       {% endfor %}
    {% endif %} -->
    <form class="mb-3" action="" method="post">
        {% csrf_token %}
        <div class="form-group mb-3 py-2 col-sm-8">
            <label for="id_new_password1" class="mb-2 fs-5">{{ form.current_password.label }}:</label>
            {% render_field form.current_password id="id_current_password" %}
        </div>
        <div class="form-group mb-3 py-2 col-sm-8">
            <label for="id_new_password1" class="mb-2 fs-5">{{ form.new_password1.label }}:</label>
            {% render_field form.new_password1 id="id_new_password1" %}
        </div>
        <div class="form-group mb-3 py-2 col-sm-8">
            <label for="new_password2" class="mb-2 fs-5">{{ form.new_password2.label }}:</label>
            {% render_field form.new_password2 id="new_password2" %}
        </div>
        <div class="row">
            <div class="col-sm-8 d-flex justify-content-between">
                <button class="btn btn-primary col-6" type="submit">Сменить пароль</button>
                <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-secondary col-sm-4 me-0">Отмена</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

src/profiles/templates/profiles/show_student_profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Application Polytech{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/student_card.css' %}?{% now 'U' %}"/>
{% endblock %}

{% block page_content %}
<div class="main_block_section col-sm-6 mb-3">
    <h3 class="fs-4 col-sm-12 text-uppercase">Мой профиль</h3>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Фамилия</div>
        <div class="col_value col-sm-6">{{ user.last_name }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Имя</div>
        <div class="col_value col-sm-6">{{ user.first_name}}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Отчество</div>
        <div class="col_value col-sm-6">{{ user.profile.middle_name }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Номер телефона</div>
        <div class="col_value col-sm-6">{{ user.profile.mobile }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Эл.почта</div>
        <div class="col_value col-sm-6">{{ user.email }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">ИНН</div>
        <div class="col_value col-sm-6">{{ user.profile.personal_number }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Дата рождения</div>
        <div class="col_value col-sm-6">{{ user.profile.birth_date|date:"SHORT_DATE_FORMAT" }} г.</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Пол</div>
        <div class="col_value col-sm-6">{{ user.profile.get_gender_display }}</div>
    </div>
    
    <div class="col-10 mb-2">
        <div class="d-flex justify-content-between">
            <a href="{% url 'profiles:edit_student_profile' %}" class="btn btn-primary col-4">Редактировать</a>
        </div>
    </div>
</div>
<div class="col-10 mb-2">
    <div class="d-flex justify-content-between">
        <a href="{% url 'profiles:password_change' %}" class="btn btn-primary col-4">Сменить пароль</a>
    </div>
</div>
{% endblock %}

src/profiles/templates/profiles/show_supervisor_profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Application Polytech{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/student_card.css' %}?{% now 'U' %}"/>
{% endblock %}

{% block page_content %}
<div class="main_block_section col-sm-6 mb-3">
    <h3 class="fs-4 col-sm-12 text-uppercase">Мой профиль</h3>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Фамилия</div>
        <div class="col_value col-sm-6">{{ user.last_name }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Имя</div>
        <div class="col_value col-sm-6">{{ user.first_name}}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Отчество</div>
        <div class="col_value col-sm-6">{{ user.profile.middle_name }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Номер телефона</div>
        <div class="col_value col-sm-6">{{ user.profile.mobile }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Email</div>
        <div class="col_value col-sm-6">{{ user.email }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">ИНН</div>
        <div class="col_value col-sm-6">{{ user.profile.personal_number }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Дата рождения</div>
        <div class="col_value col-sm-6">{{ user.profile.birth_date|date:"SHORT_DATE_FORMAT" }} г.</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Пол</div>
        <div class="col_value col-sm-6">{{ user.profile.get_gender_display }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Кафедра</div>
        <div class="col_value col-sm-6">{{ user.supervisor.department.name }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Ученое звание</div>
        <div class="col_value col-sm-6">{{ user.supervisor.academic_title.name }}</div>
    </div>
    <div class="row col-sm-12 mb-1">
        <div class="col_title col-sm-6">Ученая степень</div>
        <div class="col_value col-sm-6">{{ user.supervisor.academic_degree.name }}</div>
    </div>
    <div class="col-10 mb-2">
        <div class="d-flex justify-content-between">
            <a href="{% url 'profiles:edit_supervisor_profile' %}" class="btn btn-primary col-4">Редактировать</a>
        </div>
    </div>
</div>
<div class="col-10 mb-2">
    <div class="d-flex justify-content-between">
        <a href="{% url 'profiles:password_change' %}" class="btn btn-primary col-4">Сменить пароль</a>
    </div>
</div>
{% endblock %}