src/config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Аспирантура КГTY'

urlpatterns = [
    path('', include('main.urls')),
    path("admin/", admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('applications/', include('applications.urls')),
    path('faculty/', include('faculties.urls')),
    path('postgraduates/', include('postgraduates.urls', namespace='postgraduates')),
    path('all_study_plans/', include('study_plans.urls', namespace='all_study_plans')),
    path('study_plans/', include('study_plans.urls', namespace='student_study_plans')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/main/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    re_path(r'^login/$', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

src/postgraduates/urls.py
from django.urls import URLPattern, path
from .views import *

app_name = 'postgraduates'

urlpatterns = [
    path('personal_workspace', StudentWorkspace.as_view(), name='student_workspace'),

    path('explanatory_notes/create', CreateExplanatoryNote.as_view(), name='create_explanatory_note'),
    path('explanatory_notes/show', ShowExplanatoryNote.as_view(), name='show_explanatory_note'),
    path('explanatory_notes/<int:id>/edit', EditExplanatorySection.as_view(), name='edit_explanatory_note'),
    path('explanatory_notes/<int:id>/remove', DeleteExplanatorySection.as_view(), name='delete_explanatory_note'),
    path('dissertation_topics/<int:id>/edit', EditDissertationTopic.as_view(), name='edit_dissertation_topic'),

    path('supervisor_student/<int:id>', SupervisorStudentCard.as_view(), name='show_student_card'),
    path('supervisor_student/<int:id>/explanatory_note', SupervisorStudentExplanatoryNote.as_view(), name='show_student_explanatory_note'),

    path('explanatory_notes/<int:id>/approve', AjaxUApproveExplanatoryNote.as_view(), name='approve_explanatory_note'),
]

src/study_plans/urls.py
from django.urls import URLPattern, path
from .views import *

app_name = 'study_plans'

urlpatterns = [
    path('', ListStudyPlans.as_view(), name='index'),
    path('new', CreateStudyPlan.as_view(), name='create_study_plan'),
    path('<int:id>', ShowStudyPlan.as_view(), name='show_study_plan'),
    path('work_scope/<int:id>/new_scope_details', AddStudyWorkScopeDetails.as_view(), name='new_scope_details'),

    path('work_scope_details/<int:id>/edit', EditStudyWorkScopeDetails.as_view(), name='edit_scope_details'),
    path('work_scope_details/<int:id>/remove', DeleteStudyWorkScopeDetails.as_view(), name='remove_work_scope_details'),

    path('supervisor_student/plans/<int:id>', ShowSupervisorStudentStudyPlan.as_view(), name='show_supervisor_student_plan'),
    path('works/<int:id>', AjaxUpdateStudyPlanWorkCompletion.as_view(), name='update_work_completion'),
    path('<int:id>/change_status', AjaxUpdateStudyPlanStatus.as_view(), name='update_study_plan_status'),

]

src/study_plans/models.py
from hashlib import blake2b
from tabnanny import verbose
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse


class StudyPlanStatus(models.IntegerChoices):
    NEW = 1, 'не проверен' 
    REWORK = 3, 'доработка'
    APPROVED = 5, 'утвержден'

# Register for types of study plans
class StudyPlanType(models.Model):
    title = models.CharField(max_length=250)
    code = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    year_of_study = models.SmallIntegerField()
    sort = models.SmallIntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Тип учебного плана аспиранта'
        verbose_name_plural = '1.Справочник учебных планов - Типы учебных планов аспиранта'
        ordering = ['sort']

    def __str__(self):
        return self.title

# Register for types of works in a study plan
class WorkType(models.Model):
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    sort = models.SmallIntegerField()
    active = models.BooleanField(default=True)
    is_visible = models.BooleanField(default=True)
    is_genplan_visible = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Наименование работы'
        verbose_name_plural = '2.Справочник учебных планов - Наименования работ учебного плана'
        ordering = ['sort']

    def __str__(self):
        return self.title

# Register for types of work scope for the work in a study plan
class WorkScopeType(models.Model):
    work_type = models.ForeignKey(WorkType, on_delete=models.CASCADE, related_name='work_scope_types')
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    sort = models.SmallIntegerField()
    active = models.BooleanField(default=True)
    is_title_visible = models.BooleanField(default=True)
    code = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = 'Объем работы'
        verbose_name_plural = '3.Справочник учебных планов - Наименование объемов работ'
        ordering = ['id', 'sort', 'title']

    def __str__(self):
        return "%s: %s" % (self.work_type.title, self.title)

# Header of a study plan
class StudyPlan(models.Model):
    postgraduate = models.ForeignKey('postgraduates.Postgraduate', on_delete=models.PROTECT, related_name='study_plans')
    plan_type = models.ForeignKey(StudyPlanType, on_delete=models.SET_NULL, blank=True, null=True)
    status = models.IntegerField(choices=StudyPlanStatus.choices, default=StudyPlanStatus.NEW)
    completion_percentage = models.IntegerField(validators=[
                MinValueValidator(0),
                MaxValueValidator(100)],
                default=0
    )

    class Meta:
        verbose_name = 'Учебный план заголовок'
        verbose_name_plural = 'Учебные планы - заголовки'
        ordering = ['id']

    def get_status_css(self):
        """
        helper method for a css class used in template depending on the approval status
        """
        if self.status == 1:
            return 'status_info_primary'
        elif self.status == 3:
            return 'status_info_warning'
        else:
            return 'status_info_success'

    def recalculate_completion_percentage(self):
        works = self.study_plan_works.all()
        completion_percentage = 0
        for work in works:
            completion_percentage += work.completion_percentage

        completion_percentage = int(round(completion_percentage / works.count()))
        self.completion_percentage = completion_percentage
        self.save(update_fields=['completion_percentage'])
        return self.completion_percentage

    def __str__(self):
        return self.postgraduate.student.last_name + ' ' + self.plan_type.title

    def get_absolute_url(self):
        return reverse('student_study_plans:show_study_plan', args=[self.id])

# Study plan with a work
class StudyPlanWork(models.Model):
    study_plan = models.ForeignKey(StudyPlan, on_delete=models.PROTECT, related_name='study_plan_works')
    work_type = models.ForeignKey(WorkType, on_delete=models.PROTECT)
    completion_percentage = models.IntegerField(validators=[
                MinValueValidator(0),
                MaxValueValidator(100)],
                default=0
    )

    def left_percentage(self):
        return 100 - self.completion_percentage

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.work_type.title

# Work scope in the study plan
class StudyWorkScope(models.Model):
    study_plan_work = models.ForeignKey(StudyPlanWork, on_delete=models.PROTECT, related_name='study_work_scopes')
    work_scope = models.ForeignKey(WorkScopeType, on_delete=models.PROTECT)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.work_scope.title

# Details of a work scope in the study plan
class StudyWorkScopeDetails(models.Model):
    study_work_scope = models.ForeignKey(StudyWorkScope, on_delete=models.PROTECT, related_name='study_work_scope_details')
    subtitle = models.CharField(max_length=250, blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    subject = models.ForeignKey('faculties.Subject', on_delete=models.SET_NULL, blank=True, null=True, related_name='study_work_subjects')
    deadline = models.DateField(blank=True, null=True)
    reporting_form = models.CharField(max_length=250, blank=True, null=True)
    completion_mark = models.CharField(max_length=100, blank=True, null=True)
    faculty_conclustion = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['id']

src/study_plans/forms.py
from django import forms
from django.forms.widgets import DateInput

from .models import StudyPlanType, StudyPlan, StudyWorkScope, StudyWorkScopeDetails
from postgraduates.models import Postgraduate
from faculties.models import Subject

class NewStudyPlan(forms.ModelForm):
    class Meta:
        model = StudyPlan

        fields = ['postgraduate', 'plan_type']

    plan_type = forms.ModelChoiceField(
        required=True,
        queryset=StudyPlanType.objects.all(),
        empty_label='Учебный план не выбран'
    )

    def __init__(self, *args, **kwargs):
        self.postgraduate = kwargs.pop('postgraduate')
        super(NewStudyPlan, self).__init__(*args, **kwargs)

    # def save(self):
    #     data = self.cleaned_data
    #     # postgraduate = Postgraduate.objects.get(pk=data['postgraduate'])
    #     study_plan = StudyPlan(postgraduate=self.postgraduate,
    #                             plan_type=data['study_plan_type'])
    #     study_plan.save()
    #     return study_plan

class StudyPlanScopeDetailsCommonForm(forms.ModelForm):
    class Meta:
        model = StudyWorkScopeDetails
        fields = ['study_work_scope', 'subtitle', 'summary', 'subject', 'deadline', 'reporting_form']

        labels = {'subtitle': 'Заголовок:', 
                'summary': 'Краткое содержание:', 
                'subject': 'Дисциплина:',
                'deadline': 'Срок выполнения:',
                'reporting_form': 'Форма отчетности:'
        }

        subtitle = forms.CharField(min_length=1, max_length=250, required=False, 
                        widget=forms.TextInput()
        )
        summary = forms.CharField(required=False,
                        widget=forms.Textarea(attrs={ 'class': 'form-control', 'rows':'3', })
        )
        deadline = forms.DateField(required=True,
                        widget=DateInput(attrs={ 'type': 'date', 'class': 'form-control' })
        )
        reporting_form = forms.CharField(max_length=250, required=False,
                        widget=forms.TextInput(attrs={'class': 'form-control'})
        )
        subject = forms.ModelChoiceField(
            required=True,
            queryset=Subject.objects.all(),
            empty_label='Дисциплина не выбрана'
        )

class StudyPlanScopeDetailsForm(StudyPlanScopeDetailsCommonForm):
    class Meta(StudyPlanScopeDetailsCommonForm.Meta):
        exclude = ('subject',)

    def __init__(self, *args, **kwargs):
        self.study_work_scope = kwargs.pop('study_work_scope')
        super(StudyPlanScopeDetailsForm, self).__init__(*args, **kwargs)

class StudyPlanSubjectDetailsForm(StudyPlanScopeDetailsCommonForm):
    class Meta(StudyPlanScopeDetailsCommonForm.Meta):
        exclude = ('subtitle', 'summary', )

    def __init__(self, *args, **kwargs):
        self.study_work_scope = kwargs.pop('study_work_scope')
        super(StudyPlanSubjectDetailsForm, self).__init__(*args, **kwargs)
        self.fields['subject'].empty_label = 'Дисциплина не выбрана' 

class EditStudyPlanScopeDetailsForm(StudyPlanScopeDetailsCommonForm):
    class Meta(StudyPlanScopeDetailsCommonForm.Meta):
        exclude = ('subject',)

class EditStudyPlanSubjectDetailsForm(StudyPlanScopeDetailsCommonForm):
    class Meta(StudyPlanScopeDetailsCommonForm.Meta):
        exclude = ('subtitle', 'summary', )

src/study_plans/templates/study_plans/add_work_scope_details.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %} 

{% block title %}Study plan work scope details{% endblock %}

{% block style_head %} {% endblock %}

{% block page_content %}
<h3 class="text-sm-center fs-3 mb-3">Добавить краткое содержание и форму отчетности</h3>
<div class="study_plan_section col-sm-10 mb-2">
    <form class="mb-3" action="" method="post">
        {% csrf_token %}
        {{ form.study_work_scope.as_hidden }}
        {% if form.subject %}
            <div class="form-group mb-3 py-2 col-sm-12">
                <label for="subject" class="mb-2 fs-5">Выберите дисциплину:</label>
                {% render_field form.subject id="subject" class="form-select" %}
            </div>
        {% endif %}
        {% if form.subtitle %}
            <div class="form-group mb-2 text-sm-start">
                <label for="subtitle" class="fs-5">{{ form.subtitle.label_tag }}</label>
                {% render_field form.subtitle id="subtitle" class="form-control" type="text" %}
            </div>
        {% endif %}
        {% if form.summary %}
            <div class="form-group mb-2 text-sm-start">
                <label for="summary" class="fs-5">{{ form.summary.label_tag }}</label>
                {% render_field form.summary id="summary" class="form-control" type="textarea" %}
            </div>
        {% endif %}
        <div class="row mb-3">
            <div class="form-group col-sm-3 mb-2 text-sm-start">
                <label for="deadline" class="fs-5">{{ form.deadline.label_tag }}</label>
                <input type="date" name="deadline" value="{{ form.deadline.value|date:'Y-m-d' }}" class="form-control" >
                <!-- {#% render_field form.deadline id="deadline" class="form-control" type="date" value="form.deadline.value|date:"Y-m-d"" %} -->
            </div>
            <div class="form-group col-sm-9 mb-2 text-sm-start">
                <label for="reporting_form" class="fs-5">{{ form.reporting_form.label_tag }}</label>
                {% render_field form.reporting_form id="reporting_form" class="form-control" type="text" %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 d-flex">
                <button class="btn btn-primary col-sm-4" type="submit">Добавить</button>
                <a href="{{ view.get_success_url }}" class="btn btn-secondary col-sm-4 me-0" role="button">Отменить</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

src/study_plans/templates/study_plans/create_study_plan.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %} 

{% block title %}Study plans{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/study_plan.css' %}?{% now 'U' %}"/>
{% endblock %}

{% block page_content %}
<h3 class="text-sm-center fs-3 mb-3">Добавить учебный план работы</h3>
<div class="study_plan_section col-sm-10 mb-2">
    <form class="mb-3" action="{% url 'student_study_plans:create_study_plan' %}" method="post">
        {% csrf_token %}
        {{ form.postgraduate.as_hidden }}
        <div class="form-group mb-3 py-2 col-sm-8">
            <label for="study_plan_type" class="fw-bold mb-2 fs-5">Выберите вид учебного плана работ:</label>
            {% render_field form.plan_type id="plan_type" class="form-select" %}
        </div>
        <div class="row">
            <div class="col-sm-8 d-flex justify-content-between">
                <button class="btn btn-primary col-sm-4" type="submit">Создать</button>
                <a href="{{ view.get_success_url }}" class="btn btn-secondary col-sm-4 me-0">Отмена</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

src/study_plans/templates/study_plans/show_study_plan.html
{% extends "base.html" %}
{% load static %}

{% block title %}Study plan{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}?{% now 'U' %}"/>
{% endblock %}

{% block page_content %}
<div class="main_block_wrapper">
    <div class="w-100 col-sm-10 d-flex">
        <div class="d-inline-block col-sm-2 text-sm-center">
            <span class="{{ info_status_css }} fs-5">{{ study_plan.get_status_display }}</span>
        </div>
        <h3 class="text-sm-start fs-3 col-sm-8 ms-1">{{ study_plan.plan_type.title }}</h3>
    </div>
    {% for work in study_plan.study_plan_works.all %}
        <div class="study_plan_section col-sm-10 mb-2">
            <div class="row px-5">
                <h4 class="fs-4 col-sm-8 ms-0 ps-0">{{ work.work_type.title }}</h4>
                <div class="col-sm-2 py-2">
                    <div class="progress">
                        <div class="progress-bar bg-success" style="width:{{ work.completion_percentage }}%" role="progressbar">{{ work.completion_percentage }}</div>
                        <div class="progress-bar bg-info" style="width:{{ work.left_percentage }}%" role="progressbar"></div>
                    </div>
                </div>
            </div>
            {% for scope in work.study_work_scopes.all %}
                <div class="row px-3 pb-2">
                    <div class="card col-sm-12 mb-1">							
                        <div class="card-header fs-5 fw-bolder w-100">{{ scope.work_scope.title }}:
                            {% if study_plan_status != 5 %}
                                {% if scope.work_scope.code == 'subject' or scope.work_scope.code == 'exam' %}
                                    <a href="{% url 'student_study_plans:new_scope_details' id=scope.id %}">
                                        <img src="{% static 'images/add.png' %}" alt="edit" width="32" height="32" title="Добавить дисциплину">
                                    </a>
                                {% else %}
                                    <a href="{% url 'student_study_plans:new_scope_details' id=scope.id %}">
                                        <img src="{% static 'images/add.png' %}" alt="edit" width="32" height="32" title="Добавить содержание">
                                    </a>
                                {% endif %}
                            {% endif %}
                        </div>
                        {% for details in scope.study_work_scope_details.all %}
                            <div class="card-body row">
                                <div class="fw-bold col-sm-6">Краткое содержание работы:</div>
                                <div class="fw-bold col-sm-2">срок:</div>
                                <div class="fw-bold col-sm-2">форма отчетности:</div>
                                <div class="fw-bold col-sm-2">Действия:</div>
                                {% if scope.work_scope.code == 'subject' or scope.work_scope.code == 'exam' %}
                                    <div class="col-sm-6">
                                        {{ details.subject.name }}
                                    </div>
                                {% else %}
                                    <div class="col-sm-6">
                                        {% if details.subtitle %}
                                            {{ details.subtitle }} <br>
                                        {% endif %}
                                        {{ details.summary }}
                                    </div>
                                {% endif %}
                                <div class="col-sm-2">{{ details.deadline|date:"SHORT_DATE_FORMAT" }}</div>
                                <div class="col-sm-2">{{ details.reporting_form }}</div>
                                <div class="col-sm-2">
                                    <a href="{% url 'student_study_plans:edit_scope_details' id=details.id %}">
                                        <img src="{% static 'images/pencil.png' %}" alt="edit" width="28" height="28" title="Редактировать">
                                    </a> 
                                    <a href="{% url 'student_study_plans:remove_work_scope_details' id=details.id %}">
                                        <img src="{% static 'images/delete.png' %}" alt="edit" width="28" height="28" title="Удалить">
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</div>
{% endblock %}

src/study_plans/templates/study_plans/student_study_plans.html
{% extends "base.html" %}
{% load static %}

{% block title %}Study plans{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/study_plan.css' %}?{% now 'U' %}"/>
{% endblock %}

{% block page_content %}
<div class="main_block_wrapper">
    <h3 class="text-sm-center fs-3">Мои планы работы</h3>
    <div class="main_block_section mb-3">
        <div class="row">
            <div class="col-sm-6 fw-bold">Название плана</div>
            <div class="col-sm-3 fw-bold">Процент выполнения</div>
            <div class="col-sm-2 fw-bold">Статус</div>
            <div class="col-sm-1 fw-bold">Действия</div>
        </div>
        <hr/>
        {% for plan in study_plans %}
        <div class="row">
            <div class="col-sm-6">{{ plan.plan_type.title }}</div>
            <div class="col-sm-3">{{ plan.completion_percentage }}%</div>
            <div class="col-sm-2">{{ plan.get_status_display }}</div>
            <div class="col-sm-1">
                <a href="{% url 'student_study_plans:show_study_plan' id=plan.id %}">
                    <img src="{% static 'images/view.png' %}" alt="edit" width="28" height="28" title="Просмотреть">
                </a> 
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row text-sm-center">
        <a href="{% url 'student_study_plans:create_study_plan' %}" class="btn btn-primary w-25">
            Добавить учебный план
        </a>
    </div>
</div>
{% endblock %}

src/study_plans/templates/study_plans/supervisor_show_study_plan.html
{% extends "base.html" %}
{% load static %}

{% block title %}Study plan{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/study_plan.css' %}?{% now 'U' %}"/>
    <link rel="stylesheet" href="{% static 'css/common.css' %}?{% now 'U' %}" type="text/css">
{% endblock %}

{% block page_content %}
<div class="row">
    <div class="main_block_left col-sm-2 mb-3 text-left">
        <nav class="nav nav_left_side flex-column mt-3">
            <a class="nav-link nav_left_link" href="{% url 'postgraduates:show_student_card' id=study_plan.postgraduate.id %}">Карточка аспиранта</a>
            <a class="nav-link nav_left_link" href="{% url 'postgraduates:show_student_explanatory_note' id=study_plan.postgraduate.id %}">
                Объяснительная записка
            </a>
            {% for plan in study_plan.postgraduate.study_plans.all %}
            <a class="nav-link nav_left_link" href="{% url 'student_study_plans:show_supervisor_student_plan' id=plan.id %}">{{ plan.plan_type.title }}</a>
            {% endfor %}
        </nav>
    </div>
    <div class="main_block_center col-sm-10 mb-3">
        {% csrf_token %}
        <h4 class="text-sm-center fs-4">{{ study_plan.plan_type.title }}</h4>
        <div class="w-100 col-sm-10 d-flex fs-5 mb-1">
            <div class="d-inline-block col-sm-2 text-sm-start ms-0">
                <span class="{{ info_status_css }}" id="study_plan_status">{{ study_plan.get_status_display }}</span>
            </div>
            <div class="d-inline-block col-sm-7 text-sm-center">Аспирант: {{ study_plan.postgraduate.student.last_name }} {{ study_plan.postgraduate.student.first_name }}</div>
            <div class="d-inline-block col-sm-3 text-sm-center">
                Выполнено: <span id="total_plan_completion">{{ study_plan.completion_percentage }}</span>%
            </div>
        </div>
        {% for work in study_plan.study_plan_works.all %}
            <div class="study_plan_section col-sm-12 mb-2">
                <div class="row ps-5 pe-0">
                    <h4 class="fs-4 col-sm-8 ms-0 ps-0">{{ work.work_type.title }}</h4>
                    <div class="col-sm-2 py-2">
                        <div class="progress">
                            <div class="progress-bar bg-success" id="completion_work_{{ work.id }}" style="width:{{ work.completion_percentage }}%" role="progressbar">
                                {{ work.completion_percentage }}
                            </div>
                            <div class="progress-bar bg-info" id="left_work_{{ work.id }}" style="width:{{ work.left_percentage }}%" role="progressbar"></div>
                        </div>
                    </div>
                    <div class="col-sm-2 pt-1 m-0">
                        <button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-work_completion="{{ work.completion_percentage }}"
                                data-bs-target="#workEditModal" data-work_id="{{ work.id }}" data-work_title="{{ work.work_type.title}}" id="change_work_{{ work.id }}">
                            Задать процент
                        </button>
                    </div>
                </div>
                {% for scope in work.study_work_scopes.all %}
                    <div class="row px-3 pb-2">
                        <div class="card col-sm-12 mb-1">							
                            <div class="card-header fs-5 fw-bold w-100">{{ scope.work_scope.title }}:</div>
                            {% for details in scope.study_work_scope_details.all %}
                                <div class="card-body row">
                                    <div class="fw-bold col-sm-6">Краткое содержание работы:</div>
                                    <div class="fw-bold col-sm-2">срок:</div>
                                    <div class="fw-bold col-sm-2">форма отчетности:</div>
                                    {% if scope.work_scope.code == 'subject' or scope.work_scope.code == 'exam' %}
                                        <div class="col-sm-6">
                                            {{ details.subject.name }}
                                        </div>
                                    {% else %}
                                        <div class="col-sm-6">
                                            {% if details.subtitle %}
                                                {{ details.subtitle }} <br>
                                            {% endif %}
                                            {{ details.summary }}
                                        </div>
                                    {% endif %}
                                    <div class="col-sm-2">{{ details.deadline|date:"SHORT_DATE_FORMAT" }}</div>
                                    <div class="col-sm-2">{{ details.reporting_form }}</div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <div class="col-sm-4 pt-1 m-0">
            <button type="button" class="btn btn-outline-success btn-sm w-100" data-bs-toggle="modal" data-bs-target="#planStatusEditModal">
                Утвердить
            </button>
        </div>
    </div>
</div>

<!-- Modal change percent-->
<div class="modal fade" id="workEditModal" tabindex="-1" aria-labelledby="workEditModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header m-0">
                <h5 class="modal-title " id="workEditModalLabel">Задать процент выполнения работы</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-sm-center">
                <h6 class="modal-body-title mb-3"></h6>
                <div>
                    <input style="accent-color: #2ecc71" type="range" id="modal_slider"/>
                </div>
                <div>
                    <span>Значение: </span><span class="modal_slider_value" id="modal_slider_val"></span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary me-5" data-work_id="" id="model_save_btn" onclick="updateWorkPercentage()">Сохранить</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="modal_close_btn">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal plan approval-->
<div class="modal fade" id="planStatusEditModal" tabindex="-1" aria-labelledby="planStatusEditModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header m-0">
                <h5 class="modal-title " id="planStatusEditModalLabel">Задать статус проверки учебного плана</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5 class="modal-body-title mb-3"></h5>
                {% csrf_token %}
                <div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="approval_status" id="approval_status_reworked" value="3">
                        <label class="form-check-label" for="approval_status_reworked">
                            Отправить на доработку
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="approval_status" id="approval_status_approved" value="5" checked>
                        <label class="form-check-label" for="approval_status_approved">
                            Утвердить
                        </label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary me-5" data-section_name="" data-url="{% url 'study_plans:update_study_plan_status' id=study_plan.id %}" 
                    id="model_plan_status_save_btn" onclick="updatePlanStatus()">
                    Сохранить
                </button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="modal_plan_status_close_btn">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/work_plan_modal.js' %}"></script>
{% endblock %}