src/config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Аспирантура КГTY'

urlpatterns = [
    path('', include('main.urls')),
    path("admin/", admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('applications/', include('applications.urls')),
    path('faculty/', include('faculties.urls')),
    path('postgraduates/', include('postgraduates.urls', namespace='postgraduates')),
    path('all_study_plans/', include('study_plans.urls', namespace='all_study_plans')),
    path('study_plans/', include('study_plans.urls', namespace='student_study_plans')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/main/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    re_path(r'^login/$', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

src/postgraduates/urls.py
from django.urls import URLPattern, path
from .views import *

app_name = 'postgraduates'

urlpatterns = [
    path('personal_workspace', StudentWorkspace.as_view(), name='student_workspace'),

    path('explanatory_notes/create', CreateExplanatoryNote.as_view(), name='create_explanatory_note'),
    path('explanatory_notes/show', ShowExplanatoryNote.as_view(), name='show_explanatory_note'),
    path('explanatory_notes/<int:id>/edit', EditExplanatorySection.as_view(), name='edit_explanatory_note'),
    path('explanatory_notes/<int:id>/remove', DeleteExplanatorySection.as_view(), name='delete_explanatory_note'),
    path('dissertation_topics/<int:id>/edit', EditDissertationTopic.as_view(), name='edit_dissertation_topic'),

    path('supervisor_student/<int:id>', SupervisorStudentCard.as_view(), name='show_student_card'),
    path('supervisor_student/<int:id>/explanatory_note', SupervisorStudentExplanatoryNote.as_view(), name='show_student_explanatory_note'),

    path('explanatory_notes/<int:id>/approve', AjaxUApproveExplanatoryNote.as_view(), name='approve_explanatory_note'),
]

src/study_plans/urls.py
from django.urls import URLPattern, path
from .views import *

app_name = 'study_plans'

urlpatterns = [
    path('', ListStudyPlans.as_view(), name='index'),
    path('new', CreateStudyPlan.as_view(), name='create_study_plan'),
    path('<int:id>', ShowStudyPlan.as_view(), name='show_study_plan'),
    path('work_scope/<int:id>/new_scope_details', AddStudyWorkScopeDetails.as_view(), name='new_scope_details'),

    path('work_scope_details/<int:id>/edit', EditStudyWorkScopeDetails.as_view(), name='edit_scope_details'),
    path('work_scope_details/<int:id>/remove', DeleteStudyWorkScopeDetails.as_view(), name='remove_work_scope_details'),

    path('supervisor_student/plans/<int:id>', ShowSupervisorStudentStudyPlan.as_view(), name='show_supervisor_student_plan'),
    path('works/<int:id>', AjaxUpdateStudyPlanWorkCompletion.as_view(), name='update_work_completion'),
    path('<int:id>/change_status', AjaxUpdateStudyPlanStatus.as_view(), name='update_study_plan_status'),

]

src/postgraduates/models.py
from email.policy import default
from secrets import choice
from tabnanny import verbose
from tokenize import blank_re
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from django.utils.safestring import SafeString

class EducationType(models.TextChoices):
    NONE = 'NA', 'Не выбрано'
    FULLTIME = 'FT', 'Очное'
    DISTANCE = 'DL', 'Заочное'

class ExamGrade(models.IntegerChoices):
    NONE = -1, 'не выставлено' 
    PASSED = 0, 'зачет'
    UNSATISFACTORY = 2, 'неудовлетворительно'
    SATISFACTORY = 3, 'удовлетворительно'
    GOOD = 4, 'хорошо'
    EXCELLENT = 5, 'отлично'

class ExplanatoryNoteSectionStatus(models.IntegerChoices):
    NEW = 1, 'не проверено' 
    REWORK = 3, 'доработка'
    APPROVED = 5, 'утверждено'

# Register for types of sections in Explanatory note
class ExplanatoryNoteSectionType(models.Model):
    name = models.CharField(max_length=250)
    sort = models.SmallIntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Раздел объяснительной записки'
        verbose_name_plural = '3.Справочник разделов объяснительной записки'
        ordering = ['sort']

    def __str__(self):
        return self.name

class Postgraduate(models.Model):
    student = models.ForeignKey(User, on_delete=models.PROTECT, related_name='students')
    department = models.ForeignKey('faculties.Department', on_delete=models.SET_NULL, blank=True, null=True)
    specialty = models.ForeignKey('faculties.Specialty', on_delete=models.SET_NULL, blank=True, null=True)
    supervisor = models.ForeignKey('faculties.Supervisor', on_delete=models.SET_NULL, blank=True, null=True)
    form_of_study = models.CharField(
        max_length=2,
        choices=EducationType.choices,
        default=EducationType.NONE,
    )
    number_of_years = models.SmallIntegerField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    expected_end_date = models.DateField(blank=True, null=True)
    real_end_date = models.DateField(blank=True, null=True)

    class Meta:
        verbose_name = 'Аспирант'
        verbose_name_plural = '1.Аспиранты'
        ordering = ['id']

    def __str__(self):
        return self.student.last_name

class DissertationTopic(models.Model):
    postgraduate = models.ForeignKey(Postgraduate, on_delete=models.PROTECT, related_name='topics')
    name = HTMLField(blank=True, null=True)
    approved_by = models.CharField(max_length=250, blank=True, null=True)
    approval_date = models.DateField(blank=True, null=True)
    protocol_number = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = 'Тема диссертации'
        verbose_name_plural = '2.Темы диссертации'
        ordering = ['id']

    def __str__(self):
        return str(self.id) + ' ' + self.postgraduate.student.last_name

class ExplanatoryNoteSection(models.Model):
    postgraduate = models.ForeignKey(Postgraduate, on_delete=models.CASCADE, related_name='expl_note_sections')
    title = models.CharField(max_length=250, blank=True, null=True)
    content = HTMLField(blank=True, null=True)
    approval_status = models.IntegerField(choices=ExplanatoryNoteSectionStatus.choices, 
                                                default=ExplanatoryNoteSectionStatus.NEW)
    sort = models.IntegerField()
    is_custom = models.BooleanField(default=False)
    supervisor_comment = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['sort']

    def get_status_css(self):
        """ return a css class used in template depending on the approval status """
        if self.approval_status == 1:
            return 'status_info_primary'
        elif self.approval_status == 3:
            return 'status_info_warning'
        else:
            return 'status_info_success'

    def __str__(self):
        return self.title

class Exam(models.Model):
    postgraduate = models.ForeignKey(Postgraduate, on_delete=models.PROTECT)
    subject = models.ForeignKey('faculties.Subject', on_delete=models.PROTECT)
    date = models.DateField(blank=True, null=True)
    is_candidate_exam = models.BooleanField(default=False)
    mark = models.IntegerField(choices=ExamGrade.choices, default=ExamGrade.NONE)

    class Meta:
        verbose_name = 'Экзамен'
        verbose_name_plural = 'Экзамены'
        ordering = ['date']

    def __str__(self):
        return self.subject.name

src/postgraduates/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, ListView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import JsonResponse, Http404, HttpResponseRedirect
import json

from .models import *
from .forms import *
from main.views import StudentMenuView, SupervisorMenuView

class StudentWorkspace(LoginRequiredMixin, StudentMenuView, View):
    template_name = 'postgraduates/student_workspace.html'
    login_url = '/login/'

    def is_group_member(self, group):
        user = self.request.user
        return user.groups.filter(name=group).exists()

    def get_context_data(self, request, *args,**kwargs):
        context =  super().get_context_data(*args, **kwargs)
        user = request.user
        student = user.students.last()
        topic = student.topics.last()
        context['user'] = user
        context['student'] = student
        context['topic'] = topic
        return context

    def get(self, request, *args, **kwargs):
        if not self.is_group_member('Students'):
            return redirect('home')
        context = self.get_context_data(request)
        # assert False
        return render(request, self.template_name, context)


class EditDissertationTopic(LoginRequiredMixin, StudentMenuView, UpdateView):
    """ update dissertation topic of a student """
    # model = DissertationTopic
    form_class = EditDissertationTopicForm
    template_name = 'postgraduates/edit_dissertation_topic.html'
    pk_url_kwarg = 'id'
    login_url = '/login/'

    def get_object(self):
        return get_object_or_404(DissertationTopic, pk=self.kwargs['id'])

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def get_success_url(self):
        return reverse_lazy('postgraduates:student_workspace')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.postgraduate = self.request.user.students.last()
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class CreateExplanatoryNote(LoginRequiredMixin, StudentMenuView, CreateView):
    """ create a section in the explanatory note for student """
    form_class = NewExplanatorySectionForm
    template_name = 'postgraduates/edit_explanatory_note.html'
    login_url = '/login/'

    def get_success_url(self):
        return reverse_lazy('postgraduates:show_explanatory_note')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.postgraduate = self.request.user.students.last()
        self.object.is_custom = 1
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ShowExplanatoryNote(LoginRequiredMixin, StudentMenuView, View):
    """ shows explanatory note for student """
    template_name = 'postgraduates/show_explanatory_note.html'
    login_url = '/login/'

    def get_context_data(self, request, *args,**kwargs):
        context = super().get_context_data(*args, **kwargs)
        user = request.user
        student = user.students.last()
        expl_note_sections = student.expl_note_sections.all()
        context['expl_note_sections'] = expl_note_sections
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request)
        return render(request, self.template_name, context)


class EditExplanatorySection(LoginRequiredMixin, StudentMenuView, UpdateView):
    """ edit explanatory note  section for student """
    form_class = EditExplanatorySectionForm
    template_name = 'postgraduates/edit_explanatory_note.html'
    pk_url_kwarg = 'id'
    login_url = '/login/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_object(self):
        return get_object_or_404(ExplanatoryNoteSection, pk=self.kwargs['id'])

    def get_success_url(self):
        return reverse_lazy('postgraduates:show_explanatory_note')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.postgraduate = self.request.user.students.last()
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class DeleteExplanatorySection(LoginRequiredMixin, StudentMenuView, DeleteView):
    """ delete a section in the explanatory note """
    model = ExplanatoryNoteSection
    pk_url_kwarg = 'id'
    template_name = 'confirm_delete.html'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вы точно хотите удалить раздел объяснительной записки?'
        return context

    def get_object(self):
        return get_object_or_404(ExplanatoryNoteSection, pk=self.kwargs['id'])

    def delete(self, request, *args, **kwargs):
        expl_note_section = self.get_object()
        if expl_note_section.approval_status != 5:
            return super(DeleteExplanatorySection, self).delete(request, *args, **kwargs)
        else:
            raise Http404("Вы не можете удалить раздел")

    def get_success_url(self):
        return reverse_lazy('postgraduates:show_explanatory_note')


class SupervisorStudentCard(LoginRequiredMixin, SupervisorMenuView, DetailView):
    """ shows postgraduate card for supervisor """
    model = Postgraduate
    context_object_name = 'postgraduate'
    template_name = 'postgraduates/supervisor_student_card.html'
    pk_url_kwarg = 'id'
    login_url = '/login/'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SupervisorStudentExplanatoryNote(LoginRequiredMixin, SupervisorMenuView, View):
    """ shows postgraduate explanatory note for supervisor """
    template_name = 'postgraduates/supervisor_student_explanatory_note.html'
    pk_url_kwarg = 'id'
    login_url = '/login/'

    def get_postgraduate(self):
        return get_object_or_404(Postgraduate, pk=self.kwargs['id'])

    def get_context_data(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        postgraduate = self.get_postgraduate()
        context['postgraduate'] = postgraduate
        context['expl_note_sections'] = postgraduate.expl_note_sections.all()
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(request)
        return render(request, self.template_name, context)


class AjaxUApproveExplanatoryNote(LoginRequiredMixin, View):
    """ let supervisor to approve one section of an explanatory note """
    model = ExplanatoryNoteSection
    pk_url_kwarg = 'id'

    def get_object(self):
        return get_object_or_404(ExplanatoryNoteSection, pk=self.kwargs['id'])

    def is_ajax_request(self):
        return self.request.headers.get('x-requested-with') == 'XMLHttpRequest'

    def update_note_section_status(self, status):
        expl_note_section = self.get_object()
        expl_note_section.approval_status = status
        expl_note_section.save(update_fields=['approval_status'])
        return expl_note_section

    def post(self, request, *args, **kwargs):
        if self.is_ajax_request():
            data = json.loads(self.request.body)
            status = int(data['approval_status'])
            expl_note_section = self.update_note_section_status(status)
            approval_status = expl_note_section.get_approval_status_display()
            info_status_css = expl_note_section.get_status_css()
            response = {
                'section_id': expl_note_section.id,
                'approval_status': approval_status,
                'info_status_css': info_status_css
            }
            return JsonResponse(response)
        return redirect('home')

src/postgraduates/templates/postgraduates/edit_dissertation_topic.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit dissertation topic{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}?{% now 'U' %}"/>
    {{ form.media }}
{% endblock %}

{% block page_content %}
<div class="main_block_section mb-3">
    <h3 class="text-sm-center fs-4">Редактировать тему диссертации</h3>
    <form action="" method="POST" class="col-sm-10">
        {% csrf_token %}
        <div class="form-group mb-2 text-sm-start">
            <label for="name" class="fs-5">Тема:</label>
            {{ form.name }}
        </div>
        <div class="form-group mb-2 text-sm-start">
            <label for="approved_by" class="fs-5">Кем утверждена:</label>
            {{ form.approved_by }}
        </div>
        <div class="row mb-3">
            <div class="form-group col-sm-6 mb-2 text-sm-start">
                <label for="approval_date" class="fs-5">Дата утверждения:</label>
                {{ form.approval_date }}
            </div>
            <div class="form-group col-sm-6 mb-2 text-sm-start">
                <label for="protocol_number" class="fs-5">Номер протокола:</label>
                {{ form.protocol_number }}
            </div>
            {{ form.postgraduate.as_hidden }}
        </div>
        <div class="d-flex justify-content-between mb-3">
            <button class="btn btn-primary col-sm-4" type="submit">Сохранить</button>
            <a href="{{ view.get_success_url }}" class="btn btn-secondary col-sm-4 me-0" role="button">Отменить</a>
      </div>
    </form>
</div>
{% endblock %}

src/postgraduates/templates/postgraduates/edit_explanatory_note.html
{% extends "base.html" %}
{% load static %}
{% block title %}Edit explanatory note{% endblock %}

{% block style_head %} {{ form.media }} {% endblock %}

{% block page_content %}
<div class="main_block_section mb-3">
    <h3 class="text-sm-center fs-4">Редактировать раздел объяснительной записка</h3>
    <form class="col-10" method="POST">
        {% csrf_token %}
          {{ form.errors }}
        <div class="form-group mb-2 text-sm-start">
            <label for="title" class="fs-5">{{ form.title.label_tag }}</label>
                {{ form.title }}
        </div>
        <div class="form-group mb-2 text-sm-start">
            <label for="content" class="fs-5">{{ form.content.label_tag }}</label>
                {{ form.content }}
        </div>
        <div class="form-group mb-3 text-sm-start">
            <label for="sort" class="fs-5">{{ form.sort.label_tag }}</label>
            <div class="w-25 ms-0">
                {{ form.sort }}
            </div>
        </div>
        {{ form.is_custom.as_hidden }}
        <div class="d-flex justify-content-between">
              <button class="btn btn-primary col-sm-4" type="submit">Сохранить</button>
              <a href="{{ view.get_success_url }}" class="btn btn-secondary col-sm-4 me-0" role="button">Отменить</a>
        </div>
    </form>
</div>

{% endblock %}

src/postgraduates/templates/postgraduates/show_explanatory_note.html
{% extends "base.html" %}
{% load static %}
{% block title %}Explanatory note{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" href="{% static 'css/common.css' %}?{% now 'U' %}" type="text/css">
{% endblock %}

{% block page_content %}
<div class="main_block_section mb-3 p-2">
    <h3 class="text-sm-center fs-4">Объяснительная записка к выбору темы научной работы</h3>
    {% for section in expl_note_sections %}
        <div class="note_section col-sm-12 mb-2">
            <div class="row px-3 py-2">
                <div class="card col-sm-12 mb-1">
                    <div class="card-header row">
                        <span class="col-sm-9 fs-5 text-sm-start">{{ section.sort }}.{{ section.title }}</span>
                        <span class="status_info col-sm-2 {{ section.get_status_css }}">{{ section.get_approval_status_display }}</span>
                        <div class="col-sm-1">
                            {% if section.approval_status != 5 %}
                            <a href="{% url 'postgraduates:edit_explanatory_note' id=section.id %}">
                                <img src="{% static 'images/pencil.png' %}" alt="edit" width="28" height="28" title="Редактировать">
                            </a> 
                            <a href="{% url 'postgraduates:delete_explanatory_note' id=section.id %}">
                                <img src="{% static 'images/delete.png' %}" alt="edit" width="28" height="28" title="Удалить">
                            </a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body m-0 text-sm-start">
                        <div class="col-sm-12">{{ section.content|default_if_none:''|safe }}</div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<div class="col-10">
    <div class="d-flex justify-content-between">
          <a href="{% url 'postgraduates:create_explanatory_note' %}" class="btn btn-primary col-4">Добавить раздел</a>
    </div>
</div>
</div>
{% endblock %}

src/postgraduates/templates/postgraduates/supervisor_student_card.html
{% extends "base.html" %}
{% load static %}
{% block title %}Application Polytech{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" type="text/css" href="{% static 'css/student_card.css' %}?{% now 'U' %}"/>
    <link rel="stylesheet" href="{% static 'css/common.css' %}?{% now 'U' %}" type="text/css">
{% endblock %}

{% block page_content %}
<div class="row">
    <div class="main_block_left col-sm-2 mb-3 text-left">
        <nav class="nav nav_left_side flex-column mt-3">
            <a class="nav-link nav_left_link" href="{% url 'postgraduates:show_student_card' id=postgraduate.id %}">Карточка аспиранта</a>
            {% if postgraduate.expl_note_sections %}
            <a class="nav-link nav_left_link" href="{% url 'postgraduates:show_student_explanatory_note' id=postgraduate.id %}">Объяснительная записка</a>
            {% endif %}
            {% for plan in postgraduate.study_plans.all %}
            <a class="nav-link nav_left_link" href="{% url 'student_study_plans:show_supervisor_student_plan' id=plan.id %}">{{ plan.plan_type.title }}</a>
            {% endfor %}
        </nav>
    </div>
    <div class="main_block_center col-sm-10 mb-3">
        <div class="main_block_section col-sm-10 mb-3">
            <h3 class="fs-2 col-sm-10">Карточка аспиранта</h3>
            <div class="row col-sm-12">
                <div class="col_title col-sm-4">Факультет</div>
                <div class="col_value col-sm-6">{{ postgraduate.department.faculty.name }}</div>
            </div>
            <div class="row col-sm-12">
                <div class="col_title col-sm-4">Кафедра</div>
                <div class="col_value col-sm-6">{{ postgraduate.department.name }}</div>
            </div>
            <div class="row col-12">
                <div class="col_title col-sm-4">Форма обучения</div>
                <div class="col_value col-sm-6">{{ postgraduate.get_form_of_study_display }}</div>
            </div>
            <div class="row col-12">
                <div class="col_title col-sm-4">Срок обучения</div>
                <div class="col_value col-sm-6">{{ postgraduate.number_of_years }} г.</div>
            </div>
        </div>
        <div class="main_block_section col-sm-10 mb-3">
            <h3 class="fs-2">Индивидуальный учебный план работы аспиранта</h3>
            <div class="row col-sm-12">
                <div class="col_title col-sm-4">Фамилия, имя, отчество</div>
                <div class="col_value col-sm-6">{{ postgraduate.student.last_name }} {{ postgraduate.student.first_name }} {{ postgraduate.student.profile.middle_name }}</div>
            </div>
            <div class="row col-sm-12">
                <div class="col_title col-sm-4">Специальность</div>
                <div class="col_value col-sm-6">{{ postgraduate.specialty.code }} {{ postgraduate.specialty.name }}</div>
            </div>
            <div class="row col-sm-12 mb-2">
                <div class="col_title col-sm-4">Научный руководитель</div>
                <div class="col_value col-sm-6">Арзыбаев А.</div>
            </div>
            <div class="row col-sm-12 mb-2">
                <div class="col_title topic_title col-10 mb-2">Тема диссертации</div>
                <div class="col_value col_value_text col-10">{{ postgraduate.topics.last.name|safe }}</div>
            </div>
            <div clas="row col-sm-12">
                <div class="col_value col-9">Утверждена на совете
                    {{ postgraduate.topics.last.approved_by }}
                </div>
                <div class="col_value col-9 mb-3">дата утверждения
                    {{ postgraduate.topics.last.approval_date|default_if_none:"_____" }} г.
                    протокол № {{ postgraduate.topics.last.protocol_number|default_if_none:"_____" }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/postgraduates/templates/postgraduates/supervisor_student_explanatory_note.html
{% extends "base.html" %}
{% load static %}
{% block title %}Explanatory note{% endblock %}

{% block style_head %} 
    <link rel="stylesheet" href="{% static 'css/common.css' %}?{% now 'U' %}" type="text/css">
{% endblock %}

{% block page_content %}
<div class="row">
    <div class="main_block_left col-sm-2 mb-3 text-left">
        <nav class="nav nav_left_side flex-column mt-3">
            <a class="nav-link nav_left_link" href="{% url 'postgraduates:show_student_card' id=postgraduate.id %}">Карточка аспиранта</a>
            <a class="nav-link nav_left_link" href="{% url 'postgraduates:show_student_explanatory_note' id=postgraduate.id %}">Объяснительная записка</a>
            {% for plan in postgraduate.study_plans.all %}
            <a class="nav-link nav_left_link" href="{% url 'student_study_plans:show_supervisor_student_plan' id=plan.id %}">{{ plan.plan_type.title }}</a>
            {% endfor %}
        </nav>
    </div>
    <div class="main_block_center col-sm-10 mb-3 text-left">
        <h3 class="text-sm-center fs-4">Объяснительная записка к выбору темы научной работы</h3>
        <p class="text-sm-center fs-5">Аспиранта: {{ postgraduate.student.last_name }} {{ postgraduate.student.first_name }}</p>
       
        <div class="study_plan_section col-sm-12 mb-2">
            <div class="row px-3 py-2">
                {% for section in expl_note_sections %}
                <div class="card col-sm-12 mb-1">
                    <div class="card-header w-100 d-flex">
                        <span class="d-inline-block float-start ms-0 fs-5">{{ section.sort }}.{{ section.title }}</span>
                        <span class="d-inline-block me-1 float-end {{ section.get_status_css }}" id="section_status_{{ section.id }}">
                            {{ section.get_approval_status_display }}
                        </span>
                        <button type="button" class="btn_note_edit btn btn-outline-success btn-sm float-end" data-bs-toggle="modal" data-bs-target="#noteEditModal"
                            data-approval_status="{{ section.approval_status }}" data-section_title="{{ section.title }}" id="change_section_status_{{ section.id }}"
                            data-section_name="section_status_{{ section.id }}" data-section_id="{{ section.id }}">
                            Утвердить
                        </button>
                    </div>
                    <div class="card-body m-0 text-sm-start">
                        <div class="col-sm-12">{{ section.content|safe|default_if_none:'' }}</div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="noteEditModal" tabindex="-1" aria-labelledby="noteEditModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header m-0">
                <h5 class="modal-title " id="noteEditModalLabel">Задать статус проверки раздела</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5 class="modal-body-title mb-3"></h5>
                {% csrf_token %}
                <div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="approval_status" id="approval_status_reworked" value="3">
                        <label class="form-check-label" for="approval_status_reworked">
                            Отправить на доработку
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="approval_status" id="approval_status_approved" value="5" checked>
                        <label class="form-check-label" for="approval_status_approved">
                            Утвердить
                        </label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary me-5" data-section_name="" data-section_url="" 
                    id="model_save_btn" onclick="updateNoteStatus()">
                    Сохранить
                </button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="modal_close_btn">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static 'js/expl_note.js' %}"></script>
{% endblock %}