src/config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Аспирантура КГTY'

urlpatterns = [
    path('', include('main.urls')),
    path("admin/", admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('applications/', include('applications.urls')),
    path('faculty/', include('faculties.urls')),
    path('postgraduates/', include('postgraduates.urls', namespace='postgraduates')),
    path('all_study_plans/', include('study_plans.urls', namespace='all_study_plans')),
    path('study_plans/', include('study_plans.urls', namespace='student_study_plans')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/main/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    re_path(r'^login/$', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

src/postgraduates/urls.py
from django.urls import URLPattern, path
from .views import *

app_name = 'postgraduates'

urlpatterns = [
    path('personal_workspace', StudentWorkspace.as_view(), name='student_workspace'),

    path('explanatory_notes/create', CreateExplanatoryNote.as_view(), name='create_explanatory_note'),
    path('explanatory_notes/show', ShowExplanatoryNote.as_view(), name='show_explanatory_note'),
    path('explanatory_notes/<int:id>/edit', EditExplanatorySection.as_view(), name='edit_explanatory_note'),
    path('explanatory_notes/<int:id>/remove', DeleteExplanatorySection.as_view(), name='delete_explanatory_note'),
    path('dissertation_topics/<int:id>/edit', EditDissertationTopic.as_view(), name='edit_dissertation_topic'),

    path('supervisor_student/<int:id>', SupervisorStudentCard.as_view(), name='show_student_card'),
    path('supervisor_student/<int:id>/explanatory_note', SupervisorStudentExplanatoryNote.as_view(), name='show_student_explanatory_note'),

    path('explanatory_notes/<int:id>/approve', AjaxUApproveExplanatoryNote.as_view(), name='approve_explanatory_note'),
]

src/main/models.py
from django.db import models

class ApplicationParameters(models.Model):
    code = models.CharField(max_length=100, blank=False, unique=True)
    name = models.CharField(max_length=250, blank=False)
    value = models.CharField(max_length=250, blank=False)

    class  Meta:
        verbose_name = 'Параметр приложения'
        verbose_name_plural = 'Параметры приложения'
        ordering = ['id']

    def __str__(self):
        return self.name

class MenuShownOnPages(models.IntegerChoices):
    POSTGRADUATE    = 1, 'аспирант' 
    SUPERVISOR      = 2, 'руководитель'
    ADMINISTRATION  = 3, 'администрация'


class MenuItems(models.Model):
    title = models.CharField(max_length=50, blank=False)
    url_name = models.CharField(max_length=250, blank=False)
    sort = models.SmallIntegerField()
    seen_by = models.IntegerField(choices=MenuShownOnPages.choices, default=MenuShownOnPages.POSTGRADUATE)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Пункт меню'
        verbose_name_plural = 'Пункты меню'
        ordering = ['seen_by', 'sort']

    def __str__(self):
        return self.get_seen_by_display().upper() + ' : ' + self.title

src/main/forms.py
from django import forms

class LoginForm(forms.Form):
    user = forms.CharField(max_length=50, label='Пользователь', 
                        widget=forms.TextInput(attrs={'class':'form-control', 'id':"user", 'placeholder':'Пользователь'}))
    password = forms.CharField(max_length=50, label='Пароль',
                        widget=forms.PasswordInput(attrs={'class':'form-control', 'id':"password", 'placeholder':'Пароль'}))

src/main/views.py
import imp
from django.template import RequestContext
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, ListView, DetailView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.generic.base import ContextMixin

from main.forms import *
from .models import MenuItems

class StudentMenuView(ContextMixin):
    """ Menu items for students. """
    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["menu"] = MenuItems.objects.filter(is_active=True, seen_by=1)
        return context

class SupervisorMenuView(ContextMixin):
    """ Menu items for supervisors. """
    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["menu"] = MenuItems.objects.filter(is_active=True, seen_by=2)
        return context

class AdministrationMenuView(ContextMixin):
    """ Menu items for adiministration. """
    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["menu"] = MenuItems.objects.filter(is_active=True, seen_by=3)
        return context

class UserGroupBasedMenuView(ContextMixin):
    """ Menu items based on user group. """
    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args, **kwargs)
        user = self.request.user
        group = user.groups.last()
        context["menu"] = MenuItems.objects.filter(is_active=True, seen_by=group.id)
        return context

class HomePage(View):
    def get(self,request,*args, **kwargs):
        return render(request, 'index.html')

def user_login(request):
    next_page = ''
    if request.GET:
        next_page = request.GET['next']

    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['user']
            password = form.cleaned_data['password']
            
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(request, user)
                if next_page == "":
                    return redirect('home')
                else:
                    return redirect(next_page)
            else:
                form.add_error(None, 'Ошибка входа')
    else:
        form = LoginForm()
    
    return render(request, 'login.html', {'form': form, 'next': next_page})

def user_logout(request):
    logout(request)
    return redirect(reverse_lazy('home'))

src/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?{% now 'U' %}" type="text/css">
    {% block style_head %}
      <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
    {% endblock %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script>window.CKEDITOR_BASEPATH = '/staticfiles/ckeditor/ckeditor/';</script>
  </head>
  <body>
    <header>
      {% include 'partials/header.html' %}
    </header>
    <div class="main">
      {% include 'partials/messages.html' %}
        <!-- <div class="main_background"> -->
          <div class="container p-2">
            <div class="main_block_wrapper">
                {% block page_content %}{% endblock %}
            </div>
          </div>
        <!-- </div> -->
    </div>
    {% include 'partials/footer.html' %}
  </body>
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</html>

src/main/templates/confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Delete confirmation{% endblock %}

{% block style_head %} {% endblock %}

{% block page_content %}
<div class="main_block_wrapper">
    <div class="confirm_delete_wrapper col-sm-10 mb-2 p-2">
        <form method="POST">
            {% csrf_token %}
            <h5 class="mb-3">{{ title }}</h5>
            <div class="row">
                <div class="col-sm-12 d-flex justify-content-between">
                    <input type='submit' class="btn col-sm-3 btn-danger" value="Да, удалить">
                    <a href="{{request.META.HTTP_REFERER}}" class="btn col-sm-3 btn-secondary ml-2">Нет, вернуться назад</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

src/main/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Posgratude Polytech{% endblock %}

{% block page_content %}
<h2 class="main_title">Добро пожаловать в аспирантуру</h2>
<div class="menu-box__wrapper">
    <a href="{% url 'new_application' %}" class="menu-box__link mb-3">
        <div class="menu-square">
            <h3 class="menu-square__title pt-5 mb-5">Заявление</h3>
            <div class="menu-square__icon mt-3">
                <img src="{% static 'images/application_form.png' %}" alt="application">
            </div>
        </div>
    </a>
    <a href="{% url 'postgraduates:student_workspace' %}" class="menu-box__link mb-3">
        <div class="menu-square">
            <h3 class="menu-square__title pt-5 mb-5">Аспирант</h3>
            <div class="menu-square__icon mt-3">
                <img src="{% static 'images/student.png' %}" alt="postgratudate">
            </div>
        </div>
    </a>
    <a href="{% url 'supervisor_students' %}" class="menu-box__link mb-3">
        <div class="menu-square">
            <h3 class="menu-square__title pt-5 mb-5">Руководитель</h3>
            <div class="menu-square__icon mt-3">
                <img src="{% static 'images/professor.png' %}" alt="supervisor">
            </div>
        </div>
    </a>
    <a href="{% url 'applications' %}" class="menu-box__link mb-3">
        <div class="menu-square">
            <h3 class="menu-square__title pt-5 mb-5">Администрация</h3>
            <div class="menu-square__icon mt-3">
                <img src="{% static 'images/manager.png' %}" alt="administration">
            </div>
        </div>
    </a>
</div>
{% endblock %}

src/main/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Login Posgratude Polytech{% endblock %}
{% block style_head %} 
  <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block page_content %}
<div class="text-center">
  {% if next %}
    <form action="/login/?next={{next}}" method="post" class="form-signin w-50">
  {%else%}
  <form action="{% url 'login' %}" method="post" class="form-signin w-50">
  {% endif %}
    {% csrf_token %}
    <img class="mb-4 mt-4" src="{% static 'images/logo.png' %}" alt="logo" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal text-body">Введите данные для входа</h1>
    {% if next %}
      <input type="hidden" name="next" value="{{ next }}" />
    {% endif %}
    <div class="form-error text-danger">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <div class="form-floating mb-1">
        {{ f }}<label class="form-label" for='{{ f.id_for_label }}'>{{ f.label }}</label>
        <div class="form-error text-danger">{{ f.errors }}</div>
    </div>
    {% endfor %}
</br>
    <!-- <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div> -->
    <button type="submit" class="w-50 btn btn-lg btn-primary">Отправить</button> 
</form>
</div>
{% endblock %}